# Testing configuration for DevStream
# Optimized for fast test execution

environment: testing
debug: true
enable_vector_search: false
enable_performance_monitoring: false

database:
  db_path: ":memory:"  # In-memory database for tests
  connection_timeout: 5.0
  max_connections: 2
  wal_mode: false  # Not needed for in-memory
  cache_size: 100
  enable_vector_search: false
  enable_fts: true
  fts_tokenizer: "unicode61"

ollama:
  endpoint: "http://mock-ollama:11434"  # Mock endpoint
  timeout: 5.0
  max_retries: 1
  embedding_model: "mock-model"
  batch_size: 4
  max_workers: 1
  memory_threshold: 0.9

memory:
  max_content_length: 500
  max_memories_per_task: 10
  similarity_threshold: 0.3
  max_search_results: 5
  max_context_tokens: 200
  context_relevance_threshold: 0.3
  enable_memory_decay: false

tasks:
  max_task_duration_minutes: 1  # Fast tests
  max_task_context_tokens: 1000
  max_objectives_per_plan: 2
  max_phases_per_plan: 2
  max_tasks_per_phase: 3
  default_agent: "test-agent"
  agent_timeout: 5.0
  enable_time_tracking: false
  enable_token_tracking: false

hooks:
  enable_hooks: false  # Disable for unit tests
  hook_timeout: 1.0
  max_concurrent_hooks: 1
  force_task_creation: false
  auto_save_memory: false
  auto_inject_context: false
  hook_log_retention_days: 1

logging:
  log_level: "ERROR"  # Minimal logging in tests
  enable_structured_logging: false
  log_to_file: false
  log_to_console: false