/**
 * Test search consistency using the SAME embedding from Python test.
 * This will tell us if TypeScript gets different distances than Python.
 */

import Database from 'better-sqlite3';
import * as sqliteVec from 'sqlite-vec';
import * as fs from 'fs';

// Load the embedding generated by Python
const data = JSON.parse(fs.readFileSync('../test_query_embedding.json', 'utf-8'));
const queryEmbedding: number[] = data.embedding;

console.log('🔍 Testing Search Consistency (TypeScript)');
console.log(`Query: "${data.query}"`);
console.log(`Embedding dimensions: ${queryEmbedding.length}\n`);

// Connect to database
const db = new Database('../data/devstream.db');
sqliteVec.load(db);

console.log('📊 TypeScript Search (vec_semantic_memory):');

// Prepare embedding as vec_f32 format (JSON array)
const embeddingJson = JSON.stringify(queryEmbedding);

try {
  // CRITICAL: Use 'AND k = ?' syntax for better-sqlite3
  const stmt = db.prepare(`
    SELECT memory_id, distance, content_preview, content_type
    FROM vec_semantic_memory
    WHERE embedding MATCH vec_f32(?)
      AND k = ?
    ORDER BY distance
  `);

  const results = stmt.all(embeddingJson, 10);

  console.log(`Found: ${results.length} results\n`);

  results.slice(0, 5).forEach((row: any, i: number) => {
    const preview = row.content_preview?.substring(0, 60) || 'N/A';
    console.log(`${i + 1}. distance=${row.distance.toFixed(4)} | ${row.content_type} | ${preview}...`);
  });

  console.log('\n✅ Search completed successfully');

  // Compare with Python results
  console.log('\n🔬 Comparison with Python:');
  console.log('   If distances are IDENTICAL → Same results, no issue');
  console.log('   If distances are DIFFERENT → Found the problem!');

} catch (error) {
  console.error('❌ Error:', error instanceof Error ? error.message : String(error));
  process.exit(1);
} finally {
  db.close();
}
